<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
    <reporter-output>
    </reporter-output>
    <suite name="Default suite" duration-ms="13807" started-at="2011-08-26T10:27:23Z"
           finished-at="2011-08-26T10:27:37Z">
        <groups>
        </groups>
        <test name="Default test" duration-ms="13807" started-at="2011-08-26T10:27:23Z"
              finished-at="2011-08-26T10:27:37Z">
            <class name="com.geopresence.test.integration.GeopresenceChatTest">
                <test-method status="PASS" signature="testServerAvailability()" name="testServerAvailability"
                             is-config="true" duration-ms="62" started-at="2011-08-26T10:27:23Z"
                             finished-at="2011-08-26T10:27:23Z">
                </test-method>
                <test-method status="PASS" signature="setup()" name="setup" is-config="true" duration-ms="1693"
                             started-at="2011-08-26T10:27:23Z" finished-at="2011-08-26T10:27:24Z">
                </test-method>
                <test-method status="FAIL" signature="testChat()" name="testChat" duration-ms="7101"
                             started-at="2011-08-26T10:27:24Z" finished-at="2011-08-26T10:27:32Z">
                    <exception class="java.lang.AssertionError">
                        <full-stacktrace>
                            <![CDATA[java.lang.AssertionError
	at com.geopresence.test.integration.GeopresenceChatTest.testChat(GeopresenceChatTest.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:81)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:842)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1166)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1172)
	at org.testng.TestRunner.privateRun(TestRunner.java:757)
	at org.testng.TestRunner.run(TestRunner.java:608)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1158)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1083)
	at org.testng.TestNG.run(TestNG.java:999)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:203)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:174)
]]>
                        </full-stacktrace>
                    </exception>
                </test-method>
                <test-method status="FAIL" signature="cleanup()" name="cleanup" is-config="true" duration-ms="0"
                             started-at="2011-08-26T10:27:32Z" finished-at="2011-08-26T10:27:32Z">
                    <exception class="org.jivesoftware.smack.XMPPException">
                        <message>
                            <![CDATA[No response from server.]]>
                        </message>
                        <full-stacktrace>
                            <![CDATA[No response from server.:
	at org.jivesoftware.smack.AccountManager.deleteAccount(AccountManager.java:302)
	at com.geopresence.test.integration.GeopresenceChatTest.cleanup(GeopresenceChatTest.java:137)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:81)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:525)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:202)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:130)
	at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:222)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1172)
	at org.testng.TestRunner.privateRun(TestRunner.java:757)
	at org.testng.TestRunner.run(TestRunner.java:608)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1158)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1083)
	at org.testng.TestNG.run(TestNG.java:999)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:203)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:174)
]]>
                        </full-stacktrace>
                    </exception>
                </test-method>
            </class>
        </test>
    </suite>
</testng-results>
